### ISSUE TITLE
local typelist misnamed, should be typlist (without e) in fgen command

### ISSUE THREAD

**Issue by avila** [friosavila/stpackages#2]
I was learning from and adapting the `fgen`program when I encountered the issue. The local should be named `typlist`, without the `e`. The way it is, all variables are generated as `double`. 

From the manual (`help syntax`):

> After the syntax command, the resulting varlist is returned in \`varlist'.  If there are new variables (you coded newvarname or newvarlist), the macro \`typlist' is also defined, containing the storage type of each of the new variables, listed one after the other.  

```stata
*! v1.02 FRA Adds Characteristics Fable
*! v1.01 FRA Change fgen. Note needed to be stored without Quotes
program fgen
	syntax newvarname =/exp [if] [in] 
	local typelist double
	gen `typelist' `varlist'=`exp' 
	if strlen("`exp'")<75 {
	    label var `varlist' "`exp'"
	}
	else  {
	    label var `varlist' "See notes"
		note `varlist': `exp'
	}
	char `varlist'[fbl] "fable"
end
```

**Comment by friosavila** [comment]
Hi Marcelo (is R for Rios?)
You are right, The way I programmed this was to get every new variable as
double, because I wanted to store the information with as much precision as
possible.
The reason for that is because when margins obtains marginal effects, it
does that using numerical differentiation. I do not have control on the "h"
use for that, so I had to force the variables to be in double format.
Otherwise, the loss of precision after calling margins would grow a lot,
even for the simplest examples.

What I could do, however, is to be more explicit and if no format is called
on, use double, but if one wants to use float, it will create the variable
as such
Thank you
Fernando

**Comment by friosavila** [comment]
here is the new code

program fgen
    syntax newvarname =/exp [if] [in]
    local sm0 "`typlist'"

    set type double
    syntax newvarname =/exp [if] [in]

    gen `typlist' `varlist'=`exp'
    if strlen("`exp'")<75 {
        label var `varlist' "`exp'"
    }
    else  {
        label var `varlist' "See notes"
        note `varlist': `exp'
    }
    char `varlist'[fbl] "fable"
    set type `sm0'
end


Now, if one uses "float" it will create the variable as float. Otherwise it
will use double as default
Thanks!

**Comment by avila** [comment]
Thank you for your quick reply! No, R is for "Rainho". That would've been quite a coincidence. Also, my brother is called Fernando, actually... 😄)

I also thought that the increase in precision would be useful for the f_able purpose, but I thought it was not intentional due to similarity of typelist and typlist. 

Your suggestion for a default using `set` and the setting back is interesting. Much less complex than what I was aiming for (getting the 1 token of the command, in the cases when the user passes two arguments before `=`). I might adapt that in my use case as well :) 

Closing the issue.
